class TransmissionsSummaryObjects {
    elements = {
        transmissionDetailsHeader: () => cy.get('.styles_header__DJ849 > p'),
        transmissionHeader: () => cy.get('.styles_header__DJ849 > h2'),
        transmissionDetails: () => cy.get('.styles_summary__ieBNT > :nth-child(2)'),
        transmissionTableHeader: () => this.elements.transmissionDetails().find('b'),
        transmissionTableData: () => this.elements.transmissionDetails().find('table > tbody'),
        transmissionSubmitBtn: () => cy.get('.styles_summary__ieBNT > [data-testid="button"]'),
        transmissionDeleteBtn: () => cy.get('.styles_summary__ieBNT > .nytd-button--tertiary'),
        penaltyCard: () => cy.get('.styles_summary__uAMKQ > :nth-child(1) > :nth-child(1)'),
        penaltyCardHeader: () => this.elements.penaltyCard().find('h2'),
        penaltyCardGreen: () => this.elements.penaltyCard().find('.styles_green__LScL1'),
        penaltyCardYellow: () => this.elements.penaltyCard().find('.styles_yellow___LuGM'),
        penaltyCardFilePenalty: () => this.elements.penaltyCard().find('.styles_row__xEkRm > :nth-child(1) > .styles_subCol__W6P_J'),
        penaltyCardFileValue: () => this.elements.penaltyCard().find('.styles_row__xEkRm > :nth-child(1) > a'),
        penaltyCardDataPenalty: () => this.elements.penaltyCard().find('.styles_row__xEkRm > :nth-child(3) > .styles_subCol__W6P_J'),
        penaltyCardDataValue: () => this.elements.penaltyCard().find('.styles_row__xEkRm > :nth-child(3) > a'),
        penaltyCardSystemPenalty: () => this.elements.penaltyCard().find('.styles_row__xEkRm > :nth-child(5)'),
        penaltyCardLink: () => this.elements.penaltyCard().find('.styles_spacer__EVKX1 > a'),
        dqaCard: () => cy.get('.styles_summary__uAMKQ > :nth-child(1) > :nth-child(2)'),
        dqaCardHeader: () => this.elements.dqaCard().find('h2'),
        dqaCardElementLevel: () => this.elements.dqaCard().find('.styles_row__uEJvb > :nth-child(1)'),
        dqaCardRecordLevel: () => this.elements.dqaCard().find('.styles_row__uEJvb > :nth-child(2)'),
        dqaAdvisoryText: () => this.elements.dqaCard().find('.styles_advisoryCategoryDistribution__p2j_S'),
        dqaLink: () => this.elements.dqaCard().find('.styles_spacer__EVKX1 > a'),
        complianceCard: () => cy.get('.styles_summary__uAMKQ > :nth-child(2) > :nth-child(1)'),
        complianceCardHeader: () => this.elements.complianceCard().find('h2'),
        complianceCardElementLevel: () => this.elements.complianceCard().find('.styles_row__0YY5W > :nth-child(1)'),
        complianceCardRecordLevel: () => this.elements.complianceCard().find('.styles_row__0YY5W > :nth-child(2)'),
        complianceCardFileLevel: () => this.elements.complianceCard().find('.styles_row__0YY5W > :nth-child(3)'),
        complianceCardElementBar:() => this.elements.complianceCard().find('.styles_progressLabelText__w6WbN').eq(0),
        complianceCardRecordBar:() => this.elements.complianceCard().find('.styles_progressLabelText__w6WbN').eq(1),
        complianceCardLink: () => this.elements.complianceCard().find('.styles_spacer__EVKX1 > a'),
        fileNotesCard: () => cy.get('.styles_summary__uAMKQ > :nth-child(2) > :nth-child(2)'),
        fileNotesCardHeader: () => this.elements.fileNotesCard().find('h2'),
        fileNotesCardLink: () => this.elements.fileNotesCard().find('.styles_spacer__EVKX1 > a'),
        submissionModalHeader: () => cy.get('[aria-controls="submission_confirmation"]').find('[id="fileReviewID"]'),
        submissionModalSubheader: () => cy.get('[aria-controls="submission_confirmation"]').find('[id="modal_subtitle"]'),
        submissionModalTable: () => cy.get('[aria-controls="submission_confirmation"]').find('table > tbody').children(),
        submissionModalFooter: () => cy.get('[aria-controls="submission_confirmation"]').find('.usa-prose').eq(1),
        submissionModalSubmitBtn: () => cy.get('[aria-controls="submission_confirmation"]').find('[data-testid="button"]'),
        submissionModalCancelBtn: () => cy.get('[aria-controls="submission_confirmation"]').find('[id="undefinedCancelButton"]'),
        deleteModalHeader: () => cy.get('[aria-controls="deletion_confirmation"]').find('[id="fileReviewID"]'),
        deleteModalSubheader: () => cy.get('[aria-controls="deletion_confirmation"]').find('[id="modal_subtitle"]'),
        deleteModalTable: () => cy.get('[aria-controls="deletion_confirmation"]').find('table > tbody').children(),
        deleteModalFooter: () => cy.get('[aria-controls="deletion_confirmation"]').find('p').eq(1),
        deleteModalDeleteBtn: () => cy.get('[aria-controls="deletion_confirmation"]').find('[data-testid="button"]'),
        deleteModalCancelBtn: () => cy.get('[aria-controls="deletion_confirmation"]').find('[id="undefinedCancelButton"]'),
        summaryBreadcrumb: () => cy.get(':nth-child(3) > .styles_liOther__1TGKl'),
    }

    clickSummaryBreadcrumb() {
        this.elements.summaryBreadcrumb().click();
    }
}
export default TransmissionsSummaryObjects;